name: Run MATLAB Build on GitHub-Hosted Runner
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*'
      
permissions:
    contents: write
    
jobs:
  my-job:
    name: Run MATLAB Build
    runs-on: windows-latest
    env:
      MLM_LICENSE_TOKEN: ${{ secrets.MLM_LICENSE_TOKEN }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          products: >
            MATLAB_Coder
            
      # Add the %#codegen directive to averagingFilterCG to prompt the MATLAB Code Analyzer to identify warnings and errors specific to code generation. For code generation, input variable types must be defined. Specify the input as an unbounded vector of doubles using an arguments block.
      # codegen -config:lib -lang:c++ averagingFilterCG
      # codegen -config:lib averagingFilterCG
      - shell: cmd
        run: |
          md installation
          
      - name: Run script
        uses: matlab-actions/run-command@v2
        with:
          command: cfg = coder.config("lib"); cfg.TargetLang = "C++"; cfg.GenCodeOnly = true; cfg.Toolchain = "CMake"; codegen -config cfg myadd -c -args {zeros(1, 1), zeros(1, 1)} -d installation
      
      # - name: Run build
      #   uses: matlab-actions/run-build@v1
      #   with:
      #     tasks: sum.m
      
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "installation"
          filename: "${{ github.event.repository.name }}-${{ github.ref_name }}.zip"
        
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "installation/${{ github.event.repository.name }}-${{ github.ref_name }}.zip"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
